### ISSUE TITLE
computing reflection/refraction inside the bottle leads to an error

### ISSUE THREAD

**Issue by Nicolai46** [MarcelBrusius/Liter-Of-Light#8]
I've checked the cosine(theta_1) values in snellsLaw. If reflection/refraction is computed inside the bottle, for some rays, this value is negative, but it should be non-negative. 

Maybe this is up to the condition
` if Surface.Bottle.inShape(Light.Origin(raynum,:))`
in RayTrace, since the 'else'-case, where n1=1 and n2=1.33, should only occur for the incoming Light rays (rays outside of bottle), but the 'else'-case also occurs for rays which are inside the bottle.

**Comment by Jan-nik** [comment]
You might be on to something there ;) The origin vectors are on the bottle frame, so their numerical coordinates will be slightly outside or inside the shape. What happens if you replace this line by codeline 32?:
`norm(Light.Origin(raynum,:) - Surface.Bottle.Points(Surface.Bottle.nearestNeighbor(Light.Origin(raynum,:)),:),2) < 4.5`
